In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import os
import re

import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")

In [5]:
%time
data = pd.read_csv('data.csv')

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 9.54 µs

## Having a regular look at data

In [6]:
data.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [7]:
data.describe()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

## Data Cleaning
Fill the missing values

In [8]:
data['Volleys'].fillna(data['Volleys'].mean(), inplace=True)
data['Dribbling'].fillna(data['Dribbling'].mean(), inplace=True)
data['ShortPassing'].fillna(data['ShortPassing'].mean(), inplace=True)
data['Crossing'].fillna(data['Crossing'].mean(), inplace=True)
data['Finishing'].fillna(data['Finishing'].mean(), inplace=True)
data['HeadingAccuracy'].fillna(data['HeadingAccuracy'].mean(), inplace=True)
data['LongPassing'].fillna(data['LongPassing'].mean(), inplace=True)
data['BallControl'].fillna(data['BallControl'].mean(), inplace=True)
data['FKAccuracy'].fillna(data['FKAccuracy'].mean(), inplace=True)
data['Acceleration'].fillna(data['Acceleration'].mean(), inplace=True)
data['SprintSpeed'].fillna(data['SprintSpeed'].mean(), inplace=True)
data['Agility'].fillna(data['Agility'].mean(), inplace=True)
data['Reactions'].fillna(data['Reactions'].mean(), inplace=True)
data['Balance'].fillna(data['Balance'].mean(), inplace=True)
data['ShotPower'].fillna(data['ShotPower'].mean(), inplace=True)
data['Jumping'].fillna(data['Jumping'].mean(), inplace=True)
data['Stamina'].fillna(data['Stamina'].mean(), inplace=True)
data['Strength'].fillna(data['Strength'].mean(), inplace=True)
data['LongShots'].fillna(data['LongShots'].mean(), inplace=True)
data['Aggression'].fillna(data['Aggression'].mean(), inplace=True)
data['Interceptions'].fillna(data['Interceptions'].mean(), inplace=True)
data['Positioning'].fillna(data['Positioning'].mean(), inplace=True)
data['Penalties'].fillna(data['Penalties'].mean(), inplace=True)
data['Composure'].fillna(data['Composure'].mean(), inplace=True)
data['Marking'].fillna(data['Marking'].mean(), inplace=True)
data['StandingTackle'].fillna(data['StandingTackle'].mean(), inplace=True)
data['GKDiving'].fillna(data['GKDiving'].mean(), inplace=True)
data['GKHandling'].fillna(data['GKHandling'].mean(), inplace=True)
data['GKKicking'].fillna(data['GKKicking'].mean(), inplace=True)
data['GKPositioning'].fillna(data['GKPositioning'].mean(), inplace=True)
data['GKReflexes'].fillna(data['GKReflexes'].mean(), inplace=True)

In [9]:
data.fillna(0, inplace = True)

## Extract a column containing only unique values of the football clubs

In [13]:
unique_clubs = data['Club'].unique()

In [32]:
index = 1
with open('out.txt', 'w') as f:
    for club in unique_clubs:
        if isinstance(club, str):
            print(index,"\t",club, file=f)
            index += 1